//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KozeiDBEntities : DbContext
    {
        public KozeiDBEntities()
            : base("name=KozeiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Financial_Product> Financial_Product { get; set; }
        public DbSet<Modele> Modele { get; set; }
        public DbSet<Portfolio> Portfolio { get; set; }
        public DbSet<Portfolio_Part> Portfolio_Part { get; set; }
        public DbSet<Share> Share { get; set; }
        public DbSet<Value> Value { get; set; }
    }
}
