//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modele
    {
        public Modele()
        {
            this.Portfolio = new HashSet<Portfolio>();
            this.Value = new HashSet<Value>();
        }
    
        public int Id { get; set; }
        public Nullable<double> interest_rate { get; set; }
    
        public virtual ICollection<Portfolio> Portfolio { get; set; }
        public virtual ICollection<Value> Value { get; set; }
    }
}
