//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio_Part
    {
        public int Id { get; set; }
        public Nullable<int> portfolio_id { get; set; }
        public Nullable<int> financial_product_id { get; set; }
        public Nullable<double> part { get; set; }
        public Nullable<double> date { get; set; }
    
        public virtual Financial_Product Financial_Product { get; set; }
        public virtual Portfolio Portfolio { get; set; }
    }
}
