//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public int Id { get; set; }
        public string country { get; set; }
        public string company { get; set; }
        public string isin_code { get; set; }
        public string ticker { get; set; }
        public string path { get; set; }
    
        public virtual Financial_Product Financial_Product { get; set; }
    }
}
